version: '3'
networks:
    sw-network:
        driver: bridge
services:
    redis_service:
        build:
            dockerfile: ./docker_images/redis.dockerfile
            context: .
        image: redis_image
        container_name: redis_service
        ports:
            - "6379:6379"
        networks:
            - sw-network
    mysql_service:
        build:
            dockerfile: ./docker_images/mysql.dockerfile
            context: .
        image: mysql_image
        container_name: mysql_service
        ports:
            - "3306:3306"
        networks:
            - sw-network
    sw_server_service:
        build:
            dockerfile: ./docker_images/sw_server.dockerfile
            context: .
        image: sw_server_image
        container_name: sw_server_service
        command: bash -c "./wait-for-it.sh mysql_service:3306 && java -jar target/sw-server-1.0.jar db migrate config.yml && java -jar target/sw-server-1.0.jar server config.yml"
        ports:
            - "8080:8080"
            - "8081:8081"
        networks:
            - sw-network
        depends_on:
            - mysql_service
            - redis_service